@startuml
hide members
'skinparam handwritten true

rectangle controller {
    class WebController
}

rectangle service {
    package file {
        class FileService
    }
}

rectangle dependency {
    interface HBase
    interface OSS
    class HBaseImpl
    class OSSImpl
}

WebController --> FileService
FileService --> HBase
FileService --> OSS


HBase <|--  HBaseImpl
OSS <|-- OSSImpl
@enduml